### PR TITLE
Isolated SOAP functions in lib/infrastructure/gateway.js

### PR DESCRIPTION
**Pull request by jsuiker**
I've done a bit of rearranging to suit my own tastes... Hopefully what I've done is palatable to others and I can flesh out a few more of the SOAP endpoints in node.

### CODE REVIEW

**Comment by slogsdon** [comment]
Thanks for the contribution, @jsuiker! We're reviewing this on our end and will follow up as soon as we can.

**Comment by jsuiker** [comment]
So I'm starting to compare the existing js code to what I find in the SecureSubmit NuGet package. Now I realize that you were following a similar pattern in your function definitions and whatnot.  Is there any documentation as to what functions and parameters are preferred?  It seems the SOAP functions are well documented but I don't see any apparent documentation for the rest.

**Comment by jsuiker** [comment]
Hah, of course there is... https://developer.heartlandpaymentsystems.com/SecureSubmit/Documentation

So I guess the task at hand is to make SOAP endpoints available via the SecureSubmit API standard...

**Comment by slogsdon** [comment]
@jsuiker As you noted, we have that documentation page, which is currently in the process of being updated to cover more of the recent changes in the SDKs especially regarding new coverage of our gateway.

To answer your questions:

1. We started the SDKs as tools specifically for eCommerce merchants, but we have been working in the past few months to transition them to a state where they are applicable to more industries (retail, MOTO, etc). Because of this, we are adding more and more support for more gateway web service calls as well as the correct data groups for the various industries.
2. If you are willing to build it and it gets merged in, we would work to support it. Node.js is one of our less used SDKs, but we do treat those merchants with the same level of support.
3. We will most likely keep the name as we are transitioning the SDKs to be less SecureSubmit-specific and more general Heartland SDKs.

**Comment by jsuiker** [comment]
Hmm, if SecureSubmit was intended for eCommerce, what SDK should I be looking at for integrating Heartland payments into my Point of Sale solution?  I'll still use node regardless, but your comments about eCommerce have me wondering.

**Comment by slogsdon** [comment]
Sorry for any confusion. This SDK would be appropriate for that. We just haven't added a lot of the retail specific items to this SDK yet. Ecommerce and Retail use the same Portico calls but require different data groups/elements to be sent in the requests.

**Comment by jsuiker** [comment]
Awesome, thanks!

**Pull request closed without merging**
